name: Actualizar Tarjetas del README

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta automáticamente todos los días a la medianoche
  workflow_dispatch: # Te permite activar el robot manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Permiso para que el robot guarde las fotos en tu repo

    steps:
      - uses: actions/checkout@v4

      - name: Generar tarjeta de estadísticas
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=ChrisAlegriaR&show_icons=true&count_private=true&theme=tokyonight&hide_border=true&bg_color=00000000
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generar tarjeta de lenguajes más usados
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=ChrisAlegriaR&layout=compact&hide_border=true&theme=tokyonight&bg_color=00000000&langs_count=6&hide=jupyter%20notebook,tex,css,php&exclude_repo=Pacman-AI
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generar tarjeta de racha (Streak)
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=ChrisAlegriaR&theme=tokyonight-duo&hide_border=true
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Descargar Frase del Día Horizontal (Quotes)
        run: |
          mkdir -p profile
          curl -s "https://vercel.app" -o profile/quote.svg

      - name: Guardar imágenes en el repositorio
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards [skip ci]" || exit 0
          git push
